platform :ios, '9.0'

def app_pods
  pod 'Japx/CodableAlamofire'
  pod 'SVProgressHUD', '~> 2.1'
  pod 'AlamofireImage', '~> 3.2'
  pod 'AlamofireNetworkActivityIndicator', '~> 2.1'
end

target 'RecetasApp' do
  use_frameworks!
  app_pods
end
